# Built from:
# https://docs.github.com/en/actions/guides/building-and-testing-python

name: Build and test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install tox
      - name: Check code quality with ruff
        run: tox -e lint

  test_with_uv:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]

    runs-on: ${{ matrix.os }}


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7.3.0

      - name: setup python environment
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync 

      - name: Run tests
        run: |
         make tests
        shell: bash
        env:
          BIOPORTAL_API_KEY: ${{ secrets.BIOPORTAL_API_KEY }}
